### ISSUE TITLE
.gay ending is sus

### ISSUE THREAD

**Issue by Wjplatformer** [dotargz/webdev.gay#1]
not a criticism by any means please don't take sus seroiusly and report me to github :(

**Comment by dotargz** [comment]
hmmm...

oh btw you should join https://citrus.lol

**Comment by Wjplatformer** [comment]
Erm, maybe in about a few months. (I really DO want to join, but at this time period, no.)

**Comment by dotargz** [comment]
I have a feeling you're not quite old enough to use discord....


join anyway >:D

**Comment by Wjplatformer** [comment]
bruh. I just. HOW. I WANT TO KEEP TO THE LIMI-

**Comment by dotargz** [comment]
do or else 🔫

**Comment by Wjplatformer** [comment]
Nvm then. I already created an ema- *this is the FBI, open up. You are arrested for not being on the age limit*

**Comment by dotargz** [comment]
there are lots of under 13 people on discord... lol

**Comment by dotargz** [comment]
also i rarely use github so like

(for chatting)

**Comment by Wjplatformer** [comment]
What if I do not have access to a mobile device I can't authenticate lol

**Comment by Wjplatformer** [comment]
Also won't be online for 6 months :skull:
